# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Juhnkeplus
tagline:          'Сообщество дальнобойщиков'
description:      'Сообщество дальнобойщиков - информационный сайт'
url:              http://juhnkeplus.github.io
baseurl:          /

author:
  name:           'Juhnke'
  url:            http://juhnkeplus.github.io

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
