# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Juhnkeplus
tagline:          'Сообщество дальнобойщиков'
description:      'Сообщество дальнобойщиков - информационный сайт'
url:              http://juhnkeplus.github.io
baseurl:          /

author:
  name:           'Juhnke'
  url:            http://juhnkeplus.github.io

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

prose:
  siteurl: "https://juhnkeplus.github.io"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
    content:
      - name: "test"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      
